apiVersion: apps/v1
kind: Deployment
metadata:
  name: train-schedule-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: train-schedule
  template:
    metadata:
      labels:
        app: train-schedule
    spec:
      containers:
      - name: train-schedule
        image: kumarram260/train-schedule:latest
        ports:
        - containerPort: 8080
